// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqsMSWr-Av5RDruBNGFICg6y4WQB2qsI8',
    appId: '1:868903185653:web:9bbd18f729063b403ca9bc',
    messagingSenderId: '868903185653',
    projectId: 'pizza-app-8a84a',
    authDomain: 'pizza-app-8a84a.firebaseapp.com',
    storageBucket: 'pizza-app-8a84a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6NElX21nbbpZ8-5PjJHTMJTUO7kTCiQ',
    appId: '1:868903185653:android:51b82ab4cf5c173c3ca9bc',
    messagingSenderId: '868903185653',
    projectId: 'pizza-app-8a84a',
    storageBucket: 'pizza-app-8a84a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOlDnhaEmr_KeNJkxbUlrTT4zYBBEUWMc',
    appId: '1:868903185653:ios:424ecfdda49716203ca9bc',
    messagingSenderId: '868903185653',
    projectId: 'pizza-app-8a84a',
    storageBucket: 'pizza-app-8a84a.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOlDnhaEmr_KeNJkxbUlrTT4zYBBEUWMc',
    appId: '1:868903185653:ios:424ecfdda49716203ca9bc',
    messagingSenderId: '868903185653',
    projectId: 'pizza-app-8a84a',
    storageBucket: 'pizza-app-8a84a.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqsMSWr-Av5RDruBNGFICg6y4WQB2qsI8',
    appId: '1:868903185653:web:3be46d8192ca0b5d3ca9bc',
    messagingSenderId: '868903185653',
    projectId: 'pizza-app-8a84a',
    authDomain: 'pizza-app-8a84a.firebaseapp.com',
    storageBucket: 'pizza-app-8a84a.appspot.com',
  );
}
